# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1131, 881))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_5.setGeometry(QtCore.QRect(10, 20, 401, 361))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_cursor = QtWidgets.QLabel(self.tab)
        self.label_cursor.setGeometry(QtCore.QRect(20, 410, 81, 21))
        self.label_cursor.setObjectName("label_cursor")
        self.cursor = QtWidgets.QLineEdit(self.tab)
        self.cursor.setGeometry(QtCore.QRect(100, 410, 141, 20))
        self.cursor.setObjectName("cursor")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 400, 111, 41))
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_6.setGeometry(QtCore.QRect(10, 460, 401, 381))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(420, 20, 20, 821))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_X_lims = QtWidgets.QLabel(self.tab)
        self.label_X_lims.setGeometry(QtCore.QRect(490, 20, 41, 31))
        self.label_X_lims.setObjectName("label_X_lims")
        self.X_lims = QtWidgets.QLineEdit(self.tab)
        self.X_lims.setGeometry(QtCore.QRect(440, 50, 141, 31))
        self.X_lims.setObjectName("X_lims")
        self.label_Y_lims = QtWidgets.QLabel(self.tab)
        self.label_Y_lims.setGeometry(QtCore.QRect(490, 90, 41, 31))
        self.label_Y_lims.setObjectName("label_Y_lims")
        self.Y_lims = QtWidgets.QLineEdit(self.tab)
        self.Y_lims.setGeometry(QtCore.QRect(440, 120, 141, 31))
        self.Y_lims.setObjectName("Y_lims")
        self.label_N_chirps = QtWidgets.QLabel(self.tab)
        self.label_N_chirps.setGeometry(QtCore.QRect(490, 220, 47, 14))
        self.label_N_chirps.setObjectName("label_N_chirps")
        self.N_chirps = QtWidgets.QLineEdit(self.tab)
        self.N_chirps.setGeometry(QtCore.QRect(440, 240, 141, 31))
        self.N_chirps.setObjectName("N_chirps")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(430, 280, 161, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_Analisis = QtWidgets.QLabel(self.tab)
        self.label_Analisis.setGeometry(QtCore.QRect(490, 310, 47, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_Analisis.setFont(font)
        self.label_Analisis.setObjectName("label_Analisis")
        self.radioButton_mean = QtWidgets.QRadioButton(self.tab)
        self.radioButton_mean.setGeometry(QtCore.QRect(450, 340, 74, 18))
        self.radioButton_mean.setObjectName("radioButton_mean")
        self.radioButton_STD = QtWidgets.QRadioButton(self.tab)
        self.radioButton_STD.setGeometry(QtCore.QRect(450, 360, 74, 18))
        self.radioButton_STD.setObjectName("radioButton_STD")
        self.radioButton_max = QtWidgets.QRadioButton(self.tab)
        self.radioButton_max.setGeometry(QtCore.QRect(450, 380, 74, 18))
        self.radioButton_max.setObjectName("radioButton_max")
        self.radioButton_min = QtWidgets.QRadioButton(self.tab)
        self.radioButton_min.setGeometry(QtCore.QRect(450, 400, 74, 18))
        self.radioButton_min.setObjectName("radioButton_min")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(430, 430, 161, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_SNR = QtWidgets.QLabel(self.tab)
        self.label_SNR.setGeometry(QtCore.QRect(490, 450, 47, 14))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_SNR.setFont(font)
        self.label_SNR.setObjectName("label_SNR")
        self.label_noiise = QtWidgets.QLabel(self.tab)
        self.label_noiise.setGeometry(QtCore.QRect(480, 480, 61, 16))
        self.label_noiise.setObjectName("label_noiise")
        self.noiise = QtWidgets.QLineEdit(self.tab)
        self.noiise.setGeometry(QtCore.QRect(440, 500, 141, 31))
        self.noiise.setObjectName("noiise")
        self.label_peak = QtWidgets.QLabel(self.tab)
        self.label_peak.setGeometry(QtCore.QRect(480, 550, 51, 16))
        self.label_peak.setObjectName("label_peak")
        self.peak = QtWidgets.QLineEdit(self.tab)
        self.peak.setGeometry(QtCore.QRect(440, 580, 141, 31))
        self.peak.setObjectName("peak")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(430, 630, 161, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(583, 20, 20, 821))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(444, 780, 131, 61))
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_7.setGeometry(QtCore.QRect(600, 10, 511, 701))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.save_data = QtWidgets.QLineEdit(self.tab)
        self.save_data.setGeometry(QtCore.QRect(610, 788, 281, 51))
        self.save_data.setObjectName("save_data")
        self.toolButton_save = QtWidgets.QToolButton(self.tab)
        self.toolButton_save.setGeometry(QtCore.QRect(900, 798, 51, 31))
        self.toolButton_save.setObjectName("toolButton_save")
        self.pushButton_save = QtWidgets.QPushButton(self.tab)
        self.pushButton_save.setGeometry(QtCore.QRect(960, 780, 141, 61))
        self.pushButton_save.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_save.setObjectName("pushButton_save")
        self.scope_delay_FFT = QtWidgets.QLineEdit(self.tab)
        self.scope_delay_FFT.setGeometry(QtCore.QRect(480, 720, 101, 20))
        self.scope_delay_FFT.setObjectName("scope_delay_FFT")
        self.label_scope_delay_FFT = QtWidgets.QLabel(self.tab)
        self.label_scope_delay_FFT.setGeometry(QtCore.QRect(440, 720, 31, 16))
        self.label_scope_delay_FFT.setObjectName("label_scope_delay_FFT")
        self.label_scope_scale_FFT = QtWidgets.QLabel(self.tab)
        self.label_scope_scale_FFT.setGeometry(QtCore.QRect(440, 680, 31, 16))
        self.label_scope_scale_FFT.setObjectName("label_scope_scale_FFT")
        self.scope_scale_FFT = QtWidgets.QLineEdit(self.tab)
        self.scope_scale_FFT.setGeometry(QtCore.QRect(480, 680, 101, 20))
        self.scope_scale_FFT.setObjectName("scope_scale_FFT")
        self.label_set_scope_FFT = QtWidgets.QLabel(self.tab)
        self.label_set_scope_FFT.setGeometry(QtCore.QRect(480, 650, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_set_scope_FFT.setFont(font)
        self.label_set_scope_FFT.setObjectName("label_set_scope_FFT")
        self.label_ylog = QtWidgets.QLabel(self.tab)
        self.label_ylog.setGeometry(QtCore.QRect(490, 160, 47, 14))
        self.label_ylog.setObjectName("label_ylog")
        self.ylog = QtWidgets.QLineEdit(self.tab)
        self.ylog.setGeometry(QtCore.QRect(440, 180, 141, 31))
        self.ylog.setObjectName("ylog")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 120, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 250, 111, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 390, 111, 61))
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 800, 151, 41))
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(190, 40, 20, 811))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView.setGeometry(QtCore.QRect(490, 60, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(840, 60, 256, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_3.setGeometry(QtCore.QRect(490, 450, 256, 192))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_4.setGeometry(QtCore.QRect(850, 450, 256, 192))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.toolButton_calib = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_calib.setGeometry(QtCore.QRect(430, 730, 23, 20))
        self.toolButton_calib.setObjectName("toolButton_calib")
        self.toolButton_linear = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_linear.setGeometry(QtCore.QRect(420, 310, 23, 20))
        self.toolButton_linear.setObjectName("toolButton_linear")
        self.toolButton_flat = QtWidgets.QToolButton(self.tab_2)
        self.toolButton_flat.setGeometry(QtCore.QRect(420, 590, 23, 20))
        self.toolButton_flat.setObjectName("toolButton_flat")
        self.label_scope_IP = QtWidgets.QLabel(self.tab_2)
        self.label_scope_IP.setGeometry(QtCore.QRect(220, 0, 61, 16))
        self.label_scope_IP.setObjectName("label_scope_IP")
        self.scope_IP = QtWidgets.QLineEdit(self.tab_2)
        self.scope_IP.setGeometry(QtCore.QRect(350, 0, 113, 20))
        self.scope_IP.setObjectName("scope_IP")
        self.label_sparta_IP = QtWidgets.QLabel(self.tab_2)
        self.label_sparta_IP.setGeometry(QtCore.QRect(220, 30, 81, 16))
        self.label_sparta_IP.setObjectName("label_sparta_IP")
        self.sparta_IP = QtWidgets.QLineEdit(self.tab_2)
        self.sparta_IP.setGeometry(QtCore.QRect(350, 30, 113, 20))
        self.sparta_IP.setObjectName("sparta_IP")
        self.label_iters = QtWidgets.QLabel(self.tab_2)
        self.label_iters.setGeometry(QtCore.QRect(220, 130, 111, 16))
        self.label_iters.setObjectName("label_iters")
        self.iters = QtWidgets.QLineEdit(self.tab_2)
        self.iters.setGeometry(QtCore.QRect(350, 130, 113, 20))
        self.iters.setObjectName("iters")
        self.label_slice_ignore = QtWidgets.QLabel(self.tab_2)
        self.label_slice_ignore.setGeometry(QtCore.QRect(220, 160, 81, 16))
        self.label_slice_ignore.setObjectName("label_slice_ignore")
        self.slice_ignore = QtWidgets.QLineEdit(self.tab_2)
        self.slice_ignore.setGeometry(QtCore.QRect(350, 160, 113, 20))
        self.slice_ignore.setObjectName("slice_ignore")
        self.label_BW_range = QtWidgets.QLabel(self.tab_2)
        self.label_BW_range.setGeometry(QtCore.QRect(220, 190, 71, 16))
        self.label_BW_range.setObjectName("label_BW_range")
        self.sub_pulse_times = QtWidgets.QLineEdit(self.tab_2)
        self.sub_pulse_times.setGeometry(QtCore.QRect(350, 220, 113, 20))
        self.sub_pulse_times.setObjectName("sub_pulse_times")
        self.label_target_freq = QtWidgets.QLabel(self.tab_2)
        self.label_target_freq.setGeometry(QtCore.QRect(220, 250, 91, 16))
        self.label_target_freq.setObjectName("label_target_freq")
        self.target_freq = QtWidgets.QLineEdit(self.tab_2)
        self.target_freq.setGeometry(QtCore.QRect(350, 250, 113, 20))
        self.target_freq.setObjectName("target_freq")
        self.label_set_scope_lin = QtWidgets.QLabel(self.tab_2)
        self.label_set_scope_lin.setGeometry(QtCore.QRect(220, 280, 61, 20))
        self.label_set_scope_lin.setObjectName("label_set_scope_lin")
        self.label_scope_scale_lin = QtWidgets.QLabel(self.tab_2)
        self.label_scope_scale_lin.setGeometry(QtCore.QRect(280, 280, 31, 16))
        self.label_scope_scale_lin.setObjectName("label_scope_scale_lin")
        self.scope_scale_lin = QtWidgets.QLineEdit(self.tab_2)
        self.scope_scale_lin.setGeometry(QtCore.QRect(310, 280, 51, 20))
        self.scope_scale_lin.setObjectName("scope_scale_lin")
        self.label_scope_delay_lin = QtWidgets.QLabel(self.tab_2)
        self.label_scope_delay_lin.setGeometry(QtCore.QRect(380, 280, 31, 16))
        self.label_scope_delay_lin.setObjectName("label_scope_delay_lin")
        self.scope_delay_lin = QtWidgets.QLineEdit(self.tab_2)
        self.scope_delay_lin.setGeometry(QtCore.QRect(410, 280, 51, 20))
        self.scope_delay_lin.setObjectName("scope_delay_lin")
        self.label_lin_file_name = QtWidgets.QLabel(self.tab_2)
        self.label_lin_file_name.setGeometry(QtCore.QRect(220, 310, 47, 14))
        self.label_lin_file_name.setObjectName("label_lin_file_name")
        self.lin_file_name = QtWidgets.QLineEdit(self.tab_2)
        self.lin_file_name.setGeometry(QtCore.QRect(280, 310, 113, 20))
        self.lin_file_name.setObjectName("lin_file_name")
        self.label_by_D2S = QtWidgets.QLabel(self.tab_2)
        self.label_by_D2S.setGeometry(QtCore.QRect(220, 380, 71, 16))
        self.label_by_D2S.setObjectName("label_by_D2S")
        self.by_D2S = QtWidgets.QLineEdit(self.tab_2)
        self.by_D2S.setGeometry(QtCore.QRect(350, 380, 113, 20))
        self.by_D2S.setObjectName("by_D2S")
        self.label_V0 = QtWidgets.QLabel(self.tab_2)
        self.label_V0.setGeometry(QtCore.QRect(220, 410, 21, 16))
        self.label_V0.setObjectName("label_V0")
        self.V0 = QtWidgets.QLineEdit(self.tab_2)
        self.V0.setGeometry(QtCore.QRect(280, 410, 51, 20))
        self.V0.setObjectName("V0")
        self.label_Kd = QtWidgets.QLabel(self.tab_2)
        self.label_Kd.setGeometry(QtCore.QRect(390, 410, 21, 16))
        self.label_Kd.setObjectName("label_Kd")
        self.Kd = QtWidgets.QLineEdit(self.tab_2)
        self.Kd.setGeometry(QtCore.QRect(410, 410, 51, 20))
        self.Kd.setObjectName("Kd")
        self.label_Kp = QtWidgets.QLabel(self.tab_2)
        self.label_Kp.setGeometry(QtCore.QRect(220, 440, 21, 16))
        self.label_Kp.setObjectName("label_Kp")
        self.Kp = QtWidgets.QLineEdit(self.tab_2)
        self.Kp.setGeometry(QtCore.QRect(280, 440, 51, 20))
        self.Kp.setObjectName("Kp")
        self.label_Ki = QtWidgets.QLabel(self.tab_2)
        self.label_Ki.setGeometry(QtCore.QRect(390, 440, 21, 16))
        self.label_Ki.setObjectName("label_Ki")
        self.Ki = QtWidgets.QLineEdit(self.tab_2)
        self.Ki.setGeometry(QtCore.QRect(410, 440, 51, 20))
        self.Ki.setObjectName("Ki")
        self.label_flat_file_name = QtWidgets.QLabel(self.tab_2)
        self.label_flat_file_name.setGeometry(QtCore.QRect(220, 590, 41, 16))
        self.label_flat_file_name.setObjectName("label_flat_file_name")
        self.flat_file_name = QtWidgets.QLineEdit(self.tab_2)
        self.flat_file_name.setGeometry(QtCore.QRect(280, 590, 113, 20))
        self.flat_file_name.setObjectName("flat_file_name")
        self.label_Vbias = QtWidgets.QLabel(self.tab_2)
        self.label_Vbias.setGeometry(QtCore.QRect(220, 670, 31, 16))
        self.label_Vbias.setObjectName("label_Vbias")
        self.Vbias = QtWidgets.QLineEdit(self.tab_2)
        self.Vbias.setGeometry(QtCore.QRect(350, 670, 113, 20))
        self.Vbias.setObjectName("Vbias")
        self.label_sheet_name = QtWidgets.QLabel(self.tab_2)
        self.label_sheet_name.setGeometry(QtCore.QRect(220, 760, 61, 16))
        self.label_sheet_name.setObjectName("label_sheet_name")
        self.sheet_name = QtWidgets.QLineEdit(self.tab_2)
        self.sheet_name.setGeometry(QtCore.QRect(350, 760, 113, 20))
        self.sheet_name.setObjectName("sheet_name")
        self.label_set_scope_chip = QtWidgets.QLabel(self.tab_2)
        self.label_set_scope_chip.setGeometry(QtCore.QRect(220, 700, 61, 20))
        self.label_set_scope_chip.setObjectName("label_set_scope_chip")
        self.label_scope_scale_chip = QtWidgets.QLabel(self.tab_2)
        self.label_scope_scale_chip.setGeometry(QtCore.QRect(290, 700, 31, 16))
        self.label_scope_scale_chip.setObjectName("label_scope_scale_chip")
        self.scope_scale_chip = QtWidgets.QLineEdit(self.tab_2)
        self.scope_scale_chip.setGeometry(QtCore.QRect(320, 700, 51, 20))
        self.scope_scale_chip.setObjectName("scope_scale_chip")
        self.label_scope_delay_chip = QtWidgets.QLabel(self.tab_2)
        self.label_scope_delay_chip.setGeometry(QtCore.QRect(380, 700, 31, 16))
        self.label_scope_delay_chip.setObjectName("label_scope_delay_chip")
        self.scope_delay_chip = QtWidgets.QLineEdit(self.tab_2)
        self.scope_delay_chip.setGeometry(QtCore.QRect(410, 700, 51, 20))
        self.scope_delay_chip.setObjectName("scope_delay_chip")
        self.label_calib_file_name = QtWidgets.QLabel(self.tab_2)
        self.label_calib_file_name.setGeometry(QtCore.QRect(220, 730, 47, 14))
        self.label_calib_file_name.setObjectName("label_calib_file_name")
        self.calib_file_name = QtWidgets.QLineEdit(self.tab_2)
        self.calib_file_name.setGeometry(QtCore.QRect(290, 730, 113, 20))
        self.calib_file_name.setObjectName("calib_file_name")
        self.label_lin_dat = QtWidgets.QLabel(self.tab_2)
        self.label_lin_dat.setGeometry(QtCore.QRect(310, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_lin_dat.setFont(font)
        self.label_lin_dat.setObjectName("label_lin_dat")
        self.label_cums_dat = QtWidgets.QLabel(self.tab_2)
        self.label_cums_dat.setGeometry(QtCore.QRect(320, 350, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_cums_dat.setFont(font)
        self.label_cums_dat.setObjectName("label_cums_dat")
        self.label_chip_dat = QtWidgets.QLabel(self.tab_2)
        self.label_chip_dat.setGeometry(QtCore.QRect(310, 640, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_chip_dat.setFont(font)
        self.label_chip_dat.setObjectName("label_chip_dat")
        self.scope_scale_flat = QtWidgets.QLineEdit(self.tab_2)
        self.scope_scale_flat.setGeometry(QtCore.QRect(320, 560, 51, 20))
        self.scope_scale_flat.setObjectName("scope_scale_flat")
        self.label_scope_scale_flat = QtWidgets.QLabel(self.tab_2)
        self.label_scope_scale_flat.setGeometry(QtCore.QRect(290, 560, 31, 16))
        self.label_scope_scale_flat.setObjectName("label_scope_scale_flat")
        self.label_scope_delay_flat = QtWidgets.QLabel(self.tab_2)
        self.label_scope_delay_flat.setGeometry(QtCore.QRect(380, 560, 31, 16))
        self.label_scope_delay_flat.setObjectName("label_scope_delay_flat")
        self.scope_delay_flat = QtWidgets.QLineEdit(self.tab_2)
        self.scope_delay_flat.setGeometry(QtCore.QRect(410, 560, 51, 20))
        self.scope_delay_flat.setObjectName("scope_delay_flat")
        self.label_set_scope_flat = QtWidgets.QLabel(self.tab_2)
        self.label_set_scope_flat.setGeometry(QtCore.QRect(220, 560, 61, 20))
        self.label_set_scope_flat.setObjectName("label_set_scope_flat")
        self.label_smooth_win = QtWidgets.QLabel(self.tab_2)
        self.label_smooth_win.setGeometry(QtCore.QRect(340, 470, 61, 16))
        self.label_smooth_win.setObjectName("label_smooth_win")
        self.err_min = QtWidgets.QLineEdit(self.tab_2)
        self.err_min.setGeometry(QtCore.QRect(280, 470, 51, 20))
        self.err_min.setObjectName("err_min")
        self.smooth_win = QtWidgets.QLineEdit(self.tab_2)
        self.smooth_win.setGeometry(QtCore.QRect(410, 470, 51, 20))
        self.smooth_win.setObjectName("smooth_win")
        self.label_err_min = QtWidgets.QLabel(self.tab_2)
        self.label_err_min.setGeometry(QtCore.QRect(220, 470, 41, 16))
        self.label_err_min.setObjectName("label_err_min")
        self.label_flatness_crit = QtWidgets.QLabel(self.tab_2)
        self.label_flatness_crit.setGeometry(QtCore.QRect(360, 500, 51, 16))
        self.label_flatness_crit.setObjectName("label_flatness_crit")
        self.first_correction_ind = QtWidgets.QLineEdit(self.tab_2)
        self.first_correction_ind.setGeometry(QtCore.QRect(280, 500, 51, 20))
        self.first_correction_ind.setObjectName("first_correction_ind")
        self.flatness_crit = QtWidgets.QLineEdit(self.tab_2)
        self.flatness_crit.setGeometry(QtCore.QRect(410, 500, 51, 20))
        self.flatness_crit.setObjectName("flatness_crit")
        self.label_first_correction_ind = QtWidgets.QLabel(self.tab_2)
        self.label_first_correction_ind.setGeometry(QtCore.QRect(220, 500, 61, 16))
        self.label_first_correction_ind.setObjectName("label_first_correction_ind")
        self.BW_range = QtWidgets.QLineEdit(self.tab_2)
        self.BW_range.setGeometry(QtCore.QRect(350, 190, 113, 20))
        self.BW_range.setObjectName("BW_range")
        self.label_sub_pulse_times = QtWidgets.QLabel(self.tab_2)
        self.label_sub_pulse_times.setGeometry(QtCore.QRect(220, 220, 91, 16))
        self.label_sub_pulse_times.setObjectName("label_sub_pulse_times")
        self.Nchirps_to_average = QtWidgets.QLineEdit(self.tab_2)
        self.Nchirps_to_average.setGeometry(QtCore.QRect(410, 100, 51, 20))
        self.Nchirps_to_average.setObjectName("Nchirps_to_average")
        self.label_Nchirps = QtWidgets.QLabel(self.tab_2)
        self.label_Nchirps.setGeometry(QtCore.QRect(220, 100, 41, 16))
        self.label_Nchirps.setObjectName("label_Nchirps")
        self.label_Nchirps_to_average = QtWidgets.QLabel(self.tab_2)
        self.label_Nchirps_to_average.setGeometry(QtCore.QRect(330, 100, 81, 16))
        self.label_Nchirps_to_average.setObjectName("label_Nchirps_to_average")
        self.Nchirps = QtWidgets.QLineEdit(self.tab_2)
        self.Nchirps.setGeometry(QtCore.QRect(270, 100, 51, 20))
        self.Nchirps.setObjectName("Nchirps")
        self.label_Tos = QtWidgets.QLabel(self.tab_2)
        self.label_Tos.setGeometry(QtCore.QRect(220, 530, 81, 16))
        self.label_Tos.setObjectName("label_Tos")
        self.Tos = QtWidgets.QLineEdit(self.tab_2)
        self.Tos.setGeometry(QtCore.QRect(350, 530, 111, 20))
        self.Tos.setObjectName("Tos")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cursor.setText(_translate("MainWindow", "Cursor position"))
        self.pushButton_5.setText(_translate("MainWindow", "Set Input"))
        self.label_X_lims.setText(_translate("MainWindow", "X lims"))
        self.label_Y_lims.setText(_translate("MainWindow", "Y lims"))
        self.label_N_chirps.setText(_translate("MainWindow", "N chirps"))
        self.label_Analisis.setText(_translate("MainWindow", "Analysis:"))
        self.radioButton_mean.setText(_translate("MainWindow", "mean"))
        self.radioButton_STD.setText(_translate("MainWindow", "STD"))
        self.radioButton_max.setText(_translate("MainWindow", "max"))
        self.radioButton_min.setText(_translate("MainWindow", "min"))
        self.label_SNR.setText(_translate("MainWindow", "SNR"))
        self.label_noiise.setText(_translate("MainWindow", "Noise freqs"))
        self.label_peak.setText(_translate("MainWindow", "Peak freqs"))
        self.pushButton_6.setText(_translate("MainWindow", "Set Input"))
        self.toolButton_save.setText(_translate("MainWindow", "..."))
        self.pushButton_save.setText(_translate("MainWindow", "Save data"))
        self.label_scope_delay_FFT.setText(_translate("MainWindow", "delay"))
        self.label_scope_scale_FFT.setText(_translate("MainWindow", "time"))
        self.label_set_scope_FFT.setText(_translate("MainWindow", "Set scope:"))
        self.label_ylog.setText(_translate("MainWindow", "Y log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pushButton.setText(_translate("MainWindow", "Linearization"))
        self.pushButton_2.setText(_translate("MainWindow", "Cumsum flattening"))
        self.pushButton_3.setText(_translate("MainWindow", "Chip calib"))
        self.pushButton_4.setText(_translate("MainWindow", "Set Input"))
        self.toolButton_calib.setText(_translate("MainWindow", "..."))
        self.toolButton_linear.setText(_translate("MainWindow", "..."))
        self.toolButton_flat.setText(_translate("MainWindow", "..."))
        self.label_scope_IP.setText(_translate("MainWindow", "Scope IP"))
        self.label_sparta_IP.setText(_translate("MainWindow", "Sparta_IP"))
        self.label_iters.setText(_translate("MainWindow", "# of iterations/vector"))
        self.label_slice_ignore.setText(_translate("MainWindow", "Slices to ignore"))
        self.label_BW_range.setText(_translate("MainWindow", "BW range"))
        self.label_target_freq.setText(_translate("MainWindow", "Target Frequency"))
        self.label_set_scope_lin.setText(_translate("MainWindow", "Set scope:"))
        self.label_scope_scale_lin.setText(_translate("MainWindow", "time"))
        self.label_scope_delay_lin.setText(_translate("MainWindow", "delay"))
        self.label_lin_file_name.setText(_translate("MainWindow", "Llin file"))
        self.label_by_D2S.setText(_translate("MainWindow", "Calib by D2S"))
        self.label_V0.setText(_translate("MainWindow", "V0"))
        self.label_Kd.setText(_translate("MainWindow", "Kd"))
        self.label_Kp.setText(_translate("MainWindow", "Kp"))
        self.label_Ki.setText(_translate("MainWindow", "Ki"))
        self.label_flat_file_name.setText(_translate("MainWindow", "Flat file"))
        self.label_Vbias.setText(_translate("MainWindow", "Vbias"))
        self.label_sheet_name.setText(_translate("MainWindow", "Sheet Name"))
        self.label_set_scope_chip.setText(_translate("MainWindow", "Set scope:"))
        self.label_scope_scale_chip.setText(_translate("MainWindow", "time"))
        self.label_scope_delay_chip.setText(_translate("MainWindow", "delay"))
        self.label_calib_file_name.setText(_translate("MainWindow", "Calib file"))
        self.label_lin_dat.setText(_translate("MainWindow", "Linearization"))
        self.label_cums_dat.setText(_translate("MainWindow", "Flattening"))
        self.label_chip_dat.setText(_translate("MainWindow", "Chip Calibration"))
        self.label_scope_scale_flat.setText(_translate("MainWindow", "time"))
        self.label_scope_delay_flat.setText(_translate("MainWindow", "delay"))
        self.label_set_scope_flat.setText(_translate("MainWindow", "Set scope:"))
        self.label_smooth_win.setText(_translate("MainWindow", "Smooth win."))
        self.label_err_min.setText(_translate("MainWindow", "Err min"))
        self.label_flatness_crit.setText(_translate("MainWindow", "Flat. crit."))
        self.label_first_correction_ind.setText(_translate("MainWindow", "0 offset ind"))
        self.label_sub_pulse_times.setText(_translate("MainWindow", "Sub pulse times"))
        self.label_Nchirps.setText(_translate("MainWindow", "Nchirps"))
        self.label_Nchirps_to_average.setText(_translate("MainWindow", "Nchirps to ave."))
        self.label_Tos.setText(_translate("MainWindow", "Cor. start time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

